### PR TITLE
Add more i960 docs for MC, KB, and MX targets

### PR DESCRIPTION
**Pull request by DrItanium**
I saw this and I love this repo. Your i960VH documentation is something I don't have. Here is the docs I have on the other i960 variants. MC (Protected Architecture), KB (Numerics Architecture), MX (Extended Architecture).

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thank you!  You may want to check the email address you used in the commit.

**Comment by DrItanium** [comment]
Whoops, let me fix that

**Comment by larsbrinkhoff** [comment]
That's fine.  However, you may want to know that you can rewrite pull request any way you like.  Just git the heck out of it and do a force push to the same branch.

**Comment by DrItanium** [comment]
I did the force push after doing the git commit amend with the new author.
I realized after the fact that the pull request would have updated.

**Pull request closed without merging**
