### PR TITLE
Upload new WDC W65C02S Datasheet (Feb 25, 2020)

### PR DESCRIPTION
**Pull request by wyatt-wong**
WDC W65C02S Datasheet (Feb 25, 2020)
[wdc_w65c02s_feb_25_2020.pdf](https://github.com/larsbrinkhoff/awesome-cpus/files/7501649/wdc_w65c02s_feb_25_2020.pdf)

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I updated the pull request.  Is this what you intended to submit?

See here: https://github.com/larsbrinkhoff/awesome-cpus/pull/39/commits/142d5bffdbddf5f3e076661ae792cbe423951598

**Comment by wyatt-wong** [comment]
> 
> 
> I updated the pull request. Is this what you intended to submit?
> 
> See here: [142d5bf](https://github.com/larsbrinkhoff/awesome-cpus/commit/142d5bffdbddf5f3e076661ae792cbe423951598)

Yes. It should be located under https://github.com/larsbrinkhoff/awesome-cpus/MCS6500/

**Comment by wyatt-wong** [comment]
How come I did not see the wdc_w65c02s_feb_25_2020.pdf appear under the MCS6500 branch ?

**Comment by larsbrinkhoff** [comment]
You attached the file to the pull request description, but you didn't add the file to the commit on the branch.  So I did that for you.

**Comment by wyatt-wong** [comment]
> 
> 
> You attached the file to the pull request description, but you didn't add the file to the commit on the branch. So I did that for you.

I think I did not have the rights to commit on the branch.

**Comment by larsbrinkhoff** [comment]
That's right.  Normally you will have to make a "fork" of this repository and make a branch there.

**Pull request merged**
