### PR TITLE
Uploaded California Micro Devices G65SC02 data sheet

### PR DESCRIPTION
**Pull request by wyatt-wong**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
This seems to have settled now, so I'll look into it.

**Comment by larsbrinkhoff** [comment]
There are many commits in this pull request, and they touch both MCS6500 and MC6809 directories.  Please resubmit two separate pull request with one commit each.

**Comment by wyatt-wong** [comment]
> There are many commits in this pull request, and they touch both MCS6500 and MC6809 directories.  Please resubmit two separate pull request with one commit each.

I found that I was unable to create 2 separate pull requests. After I forked your GitHub page into my own GitHub page and I started updating, I have to start a pull request.

After that when I go back to your page and fork again, I will end up going to my own GitHub page and whenever I add or remove something it will be using the previous pull request and I could not create a new pull request unless my last pull request have been committed by you.

**Comment by wyatt-wong** [comment]
> There are many commits in this pull request, and they touch both MCS6500 and MC6809 directories. Please resubmit two separate pull request with one commit each.

Is there any update?

**Comment by larsbrinkhoff** [comment]
Sorry, I don't have time to guide you.  My previous comment still stands.

**Comment by wyatt-wong** [comment]
Cancelled Pull Request

**Pull request closed without merging**
